# Generated by Django 2.1.7 on 2019-06-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20190613_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=200)),
                ('observations', models.TextField(max_length=200)),
                ('is_return', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=4)),
                ('rapport', models.TextField(max_length=200, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient')),
                ('secretary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.Secretary')),
            ],
        ),
    ]
