# Generated by Django 2.1.7 on 2019-06-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20190613_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Secretary'),
        ),
    ]
