# Generated by Django 2.1.7 on 2019-06-17 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20190613_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_string',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.Doctor'),
        ),
    ]
