# Generated by Django 2.1.7 on 2019-06-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_auto_20190617_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['time_int']},
        ),
        migrations.AddField(
            model_name='time',
            name='time_int',
            field=models.IntegerField(null=True),
        ),
    ]
