# Generated by Django 2.1.7 on 2019-06-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20190617_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={},
        ),
        migrations.RemoveField(
            model_name='time',
            name='time_int',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_int',
            field=models.IntegerField(null=True),
        ),
    ]
